version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
volumes:
  db_data:
